### PR TITLE
initial link from Results-view to Dish-view and random background images and buttons added to grid results

### PR DESCRIPTION
**Pull request by itsmalk**

### CODE REVIEW

**Comment by syousif94** [comment]
Excellent work so far. Here's what's needed before merging.

- [ ] Add ```paddingTop: 20``` to ```styles.content``` in ```SearchResults.js```.
- [ ] Make a new component for the stuff in renderItem. Call it whatever you want.
- [ ] Add a drop shadow to the TouchableOpacity [Shadow Props](https://facebook.github.io/react-native/docs/shadow-props.html)
- [ ] Add a 0.5 pt black border to the TouchableOpacity.
- [ ] Create components for the buttons in the attached screenshot. Position them absolutely and only wrap the icon and text in TouchableOpacity, not the transparent background. Feel free to use your best judgement on the padding.
- [ ] Delete ```duration={1}``` in the dish scene component in ```Nav.js```. Timing is in milliseconds btw.

[sprinkle.sketch.zip](https://github.com/txcsmad/sprinkle/files/846455/sprinkle.sketch.zip)
iphone 7

**Comment by itsmalk** [comment]
Alright, I made those changes! Let me know what you think

**Comment by itsmalk** [comment]
Alright, those changes are in! Let me know what you think

**Comment by syousif94** [comment]
I like that you bumped up the sizes of the text and the icons, but it looks like you didn't resize the assets in sketch before exporting them. These are raster graphics so they look grainy if you don't export them at the right size. Also, a lot of the component styling isn't taking full advantage of flexbox. I'm gonna fix both of these issues now before merging. Please take a look at the changes after I do, as I think it'll help when styling future components. Other than that, great job. It feels like you're picking up React Native very quickly.

**Comment by itsmalk** [comment]
Got it, thanks for the notes. I had a feeling that there were things I was missing with flexbox.

**Pull request merged**
